import {
  app,
  BrowserWindow,
  globalShortcut,
  Menu,
  Tray,
  ipcMain,
} from "electron";
import path from "path";
import fs from "fs";
import { exec } from "child_process";
import admZip from "adm-zip";

import { IEnvVars } from "./types/EnvVarsTypes";
import { IDownloadFile, IRunUrlArgs, IUnzipFile } from "./types/ElectronTypes";
import * as os from "os";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      // devTools: !app.isPackaged, // Enable/Disable devTools
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  // Get CPU information
  const cpuArch = os.arch();
  const cpuType = os.cpus()[0].model;

  // Send CPU information to renderer process
  mainWindow.webContents.on("did-finish-load", () => {
    mainWindow.webContents.send("cpu-info", { arch: cpuArch, type: cpuType });
  });
};

const openWindow = () => {
  const windows = BrowserWindow.getAllWindows();
  if (windows.length === 0) {
    createWindow();
  } else {
    windows[0].focus();
  }
};

const createTray = () => {
  const tray = new Tray("src/assets/main/NewLogoHead.png");
  const contextMenu = Menu.buildFromTemplate([
    { label: "tymt 0.1.0", enabled: false },
    {
      label: "Open tymt",
      role: "window",
      accelerator: "Alt+T",
      click: () => openWindow(),
    },
    { type: "separator" },
    { label: "Exit", click: () => app.quit() },
  ]);
  tray.setToolTip("This is my application.");
  tray.setTitle("tymt");
  tray.setContextMenu(contextMenu);

  tray.on("click", () => openWindow());
};

const registerGlobalShortcut = () => {
  globalShortcut.register("Alt+T", () => openWindow());
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.

app
  .whenReady()
  .then(createTray)
  .then(registerGlobalShortcut)
  .then(createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  console.log("window-all-closed", process.platform);
  if (process.platform !== "darwin") {
    console.log("app.quit");
    // app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  openWindow();
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

ipcMain.handle("getEnvVars", () => {
  const envVars: IEnvVars = {
    CONFIG_PRODUCTION_VERSION: process.env.APP_PRODUCTION_VERSION,
    CONFIG_NETWORK_NAME: process.env.APP_NETWORK_NAME,

    CONFIG_TYMT_BACKEND_URL:
      process.env.APP_PRODUCTION_VERSION === "prod"
        ? process.env.APP_TYMT_BACKEND_URL
        : process.env.APP_TYMT_BACKEND_DEV_URL,
    CONFIG_TYMT_SOCKET_BACKEND_URL:
      process.env.APP_PRODUCTION_VERSION === "prod"
        ? process.env.APP_SOCKET_BACKEND_URL
        : process.env.APP_SOCKET_BACKEND_DEV_URL,
    CONFIG_TYMT_AVATAR_URL:
      process.env.APP_PRODUCTION_VERSION === "prod"
        ? process.env.APP_TYMT_AVATAR_URL
        : process.env.APP_TYMT_AVATAR_DEV_URL,

    CONFIG_TYMT_RELEASE_DATE: process.env.APP_TYMT_RELEASE_DATE,
    CONFIG_TYME_VERSION: process.env.APP_TYMT_VERSION,

    CONFIG_SOLAR_API_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_SOLAR_API_URL
        : process.env.APP_TESTNET_SOLAR_API_URL,
    CONFIG_SOLAR_WSS_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_SOLAR_WSS_URL
        : process.env.APP_TESTNET_SOLAR_WSS_URL,

    CONFIG_SOLAR_SCAN:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_SOLAR_SCAN
        : process.env.APP_TESTNET_SOLAR_SCAN,
    CONFIG_ETH_SCAN:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_ETH_SCAN
        : process.env.APP_TESTNET_ETH_SCAN,
    CONFIG_ARB_SCAN:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_ARB_SCAN
        : process.env.APP_TESTNET_ARB_SCAN,
    CONFIG_AVAX_SCAN:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_AVAX_SCAN
        : process.env.APP_TESTNET_AVAX_SCAN,
    CONFIG_BSC_SCAN:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_BSC_SCAN
        : process.env.APP_TESTNET_BSC_SCAN,
    CONFIG_OPT_SCAN:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_OPT_SCAN
        : process.env.APP_TESTNET_OPT_SCAN,
    CONFIG_POL_SCAN:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_POL_SCAN
        : process.env.APP_TESTNET_POL_SCAN,
    CONFIG_BTC_SCAN:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_BTC_SCAN
        : process.env.APP_TESTNET_BTC_SCAN,
    CONFIG_SOL_SCAN:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_SOL_SCAN
        : process.env.APP_TESTNET_SOL_SCAN,

    CONFIG_BSC_API_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_BSC_API_URL
        : process.env.APP_TESTNET_BSC_API_URL,
    CONFIG_ETH_API_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_ETH_API_URL
        : process.env.APP_TESTNET_ETH_API_URL,
    CONFIG_POL_API_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_POL_API_URL
        : process.env.APP_TESTNET_POL_API_URL,
    CONFIG_OP_API_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_OP_API_URL
        : process.env.APP_TESTNET_OP_API_URL,
    CONFIG_ARB_API_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_ARB_API_URL
        : process.env.APP_TESTNET_ARB_API_URL,
    CONFIG_AVAX_API_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_AVAX_API_URL
        : process.env.APP_TESTNET_AVAX_API_URL,
    CONFIG_BTC_API_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_BTC_API_URL
        : process.env.APP_TESTNET_BTC_API_URL,

    CONFIG_ALCHEMY_KEY: process.env.APP_ALCHEMY_KEY,

    CONFIG_BSC_RPC_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_BSC_RPC_URL
        : process.env.APP_TESTNET_BSC_RPC_URL,
    CONFIG_ETH_RPC_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_ETH_RPC_URL + process.env.APP_ALCHEMY_KEY
        : process.env.APP_TESTNET_ETH_RPC_URL + process.env.APP_ALCHEMY_KEY,
    CONFIG_POL_RPC_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_POL_RPC_URL + process.env.APP_ALCHEMY_KEY
        : process.env.APP_TESTNET_POL_RPC_URL + process.env.APP_ALCHEMY_KEY,
    CONFIG_OP_RPC_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_OP_RPC_URL + process.env.APP_ALCHEMY_KEY
        : process.env.APP_TESTNET_OP_RPC_URL + process.env.APP_ALCHEMY_KEY,
    CONFIG_ARB_RPC_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_ARB_RPC_URL + process.env.APP_ALCHEMY_KEY
        : process.env.APP_TESTNET_ARB_RPC_URL + process.env.APP_ALCHEMY_KEY,
    CONFIG_AVAX_RPC_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_AVAX_PROVIDER
        : process.env.APP_TESTNET_AVAX_PROVIDER,

    CONFIG_BSC_API_KEY: process.env.APP_BSC_API_KEY,
    CONFIG_ETH_API_KEY: process.env.APP_ETH_API_KEY,
    CONFIG_POL_API_KEY: process.env.APP_POL_API_KEY,
    CONFIG_OP_API_KEY: process.env.APP_OP_API_KEY,
    CONFIG_ARB_API_KEY: process.env.APP_ARB_API_KEY,
  };
  return envVars;
});

ipcMain.handle("getPlatform", () => process.platform);

ipcMain.handle("getArch", () => process.arch);

ipcMain.handle("getAppPath", () => {
  const appPath = `${app.getPath("appData")}/tymtLauncher`;

  if (!fs.existsSync(appPath)) {
    fs.mkdirSync(appPath, { recursive: true });
  }

  return appPath;
});

ipcMain.handle(
  "download-file",
  async (event, { downloadLink, downloadPath }: IDownloadFile) => {
    const win = BrowserWindow.getFocusedWindow();

    win.webContents.downloadURL(downloadLink);

    win.webContents.session.on("will-download", (event, item) => {
      // Set save path
      item.setSavePath(downloadPath);

      // Monitor progress
      item.on("updated", (event, state) => {
        if (state === "interrupted") {
          console.log("Download is interrupted but can be resumed");
        } else if (state === "progressing") {
          if (item.isPaused()) {
            console.log("Download is paused");
          } else {
            const progress = item.getReceivedBytes() / item.getTotalBytes();
            win.webContents.send("download-progress", progress * 100); // Send progress to renderer
          }
        }
      });

      // Download completed
      item.once("done", (event, state) => {
        if (state === "completed") {
          console.log("Download successful");
          win.webContents.send("download-complete", downloadPath);
        } else {
          console.error("Download failed");
          win.webContents.send("download-failed");
        }
      });
    });
  }
);

ipcMain.handle(
  "unzip-file",
  (event, { fileLocation, installDir }: IUnzipFile) => {
    try {
      const zip = new admZip(fileLocation);
      zip.extractAllTo(installDir);
    } catch (error) {
      console.error("Error unzipping file:", error);
    }
  }
);

ipcMain.handle(
  "move-app-image-linux",
  async (event, { fileLocation, installDir }: IUnzipFile) => {
    const sourcePath = path.resolve(fileLocation);
    const fileName = path.basename(sourcePath);
    const destinationPath = path.join(installDir, fileName);

    // Ensure the parent directory exists
    const parentDir = path.dirname(destinationPath);
    if (!fs.existsSync(parentDir)) {
      fs.mkdirSync(parentDir, { recursive: true });
    }

    // Move the file
    try {
      fs.renameSync(sourcePath, destinationPath);
    } catch (error) {
      throw new Error(`Failed to move file: ${error.message}`);
    }
  }
);

ipcMain.handle(
  "un-tar-bz2-macos",
  (event, { fileLocation, installDir }: IUnzipFile) => {
    const installPath = path.resolve(installDir);

    // Create the directory if it doesn't exist
    if (!fs.existsSync(installPath)) {
      fs.mkdirSync(installPath, { recursive: true });
    }

    exec(
      `tar -xvjf "${fileLocation}" -C "${installDir}"`,
      (error, stdout, stderr) => {
        if (error) {
          throw new Error(`Failed to unzip: ${stderr || error.message}`);
        }
      }
    );
  }
);

ipcMain.handle("set-permission", (event, executablePath: string) => {
  // Check if the file exists
  if (!fs.existsSync(executablePath)) {
    throw new Error(`File does not exist: ${executablePath}`);
  }

  // Set the executable permission
  try {
    // On Unix-like systems, use fs.chmod to set permissions
    fs.chmodSync(executablePath, 0o755); // Set permissions to rwxr-xr-x
  } catch (error) {
    throw new Error(`Failed to set permissions: ${error.message}`);
  }
});

ipcMain.handle("delete-file", (event, filePath: string) => {
  fs.unlinkSync(filePath);
});

ipcMain.handle("run-url-args", (event, { url, args }: IRunUrlArgs) => {
  console.log(url);
  args.forEach((arg) => {
    console.log(arg);
  });

  const commandPath = url === "open" ? args[1] : url;
  const workingDirectory = path.dirname(commandPath);

  console.log(`Setting working directory to: ${workingDirectory}`);

  const command = exec(commandPath, { cwd: workingDirectory });

  command.stdout.on("data", (data) => {
    console.log(`Output: ${data}`);
  });

  command.stderr.on("data", (data) => {
    console.error(`Error: ${data}`);
  });

  command.on("close", (code) => {
    console.log(`Process exited with code: ${code}`);
  });

  if (args.length > 0) {
    args.forEach((arg) => {
      command.stdin.write(`${arg} `);
    });
    command.stdin.end();
  } else {
    console.log("No command provided");
  }
});
