import { app, BrowserWindow, globalShortcut, Menu, Tray, ipcMain, shell } from "electron";
import * as os from "os";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      // devTools: !app.isPackaged, // Enable/Disable devTools
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  // Get CPU information
  const cpuArch = os.arch();
  const cpuType = os.cpus()[0].model;
  const osType = os.type();

  // Send CPU information to renderer process
  mainWindow.webContents.on("did-finish-load", () => {
    mainWindow.webContents.send("sys-info", { cpuArch: cpuArch, cpuType: cpuType, osType: osType });
  });
};

const openWindow = () => {
  const windows = BrowserWindow.getAllWindows();
  if (windows.length === 0) {
    createWindow();
  } else {
    windows[0].focus();
  }
};

const createTray = () => {
  const tray = new Tray("src/assets/main/NewLogoHead.png");
  const contextMenu = Menu.buildFromTemplate([
    { label: "tymt 0.1.0", enabled: false },
    {
      label: "Open tymt",
      role: "window",
      accelerator: "Alt+T",
      click: () => openWindow(),
    },
    { type: "separator" },
    { label: "Exit", click: () => app.quit() },
  ]);
  tray.setToolTip("This is my application.");
  tray.setTitle("tymt");
  tray.setContextMenu(contextMenu);

  tray.on("click", () => openWindow());
};

const registerGlobalShortcut = () => {
  globalShortcut.register("Alt+T", () => openWindow());
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.

app.whenReady().then(createTray).then(registerGlobalShortcut).then(createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  // if (process.platform !== "darwin") {
  //   app.quit();
  // }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  openWindow();
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

// Listen for IPC messages to open external links
ipcMain.on("open-external-link", (event, url) => {
  shell.openExternal(url);
});
