import { app, BrowserWindow, globalShortcut, Menu, Tray, ipcMain } from "electron";
import { IEnvVars } from "./types/EnvVarsTypes";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      // devTools: !app.isPackaged, // Enable/Disable devTools
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

const openWindow = () => {
  const windows = BrowserWindow.getAllWindows();
  if (windows.length === 0) {
    createWindow();
  } else {
    windows[0].focus();
  }
};

const createTray = () => {
  const tray = new Tray("src/assets/main/NewLogoHead.png");
  const contextMenu = Menu.buildFromTemplate([
    { label: "tymt 0.1.0", enabled: false },
    {
      label: "Open tymt",
      role: "window",
      accelerator: "Alt+T",
      click: () => openWindow(),
    },
    { type: "separator" },
    { label: "Exit", click: () => app.quit() },
  ]);
  tray.setToolTip("This is my application.");
  tray.setTitle("tymt");
  tray.setContextMenu(contextMenu);

  tray.on("click", () => openWindow());
};

const registerGlobalShortcut = () => {
  globalShortcut.register("Alt+T", () => openWindow());
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.

app
  .whenReady()
  .then(createTray)
  .then(registerGlobalShortcut)
  .then(createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  // if (process.platform !== "darwin") {
  //   app.quit();
  // }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  openWindow();
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

ipcMain.handle("getEnvVars", async () => {
  const envVars: IEnvVars = {
    CONFIG_PRODUCTION_VERSION: process.env.APP_PRODUCTION_VERSION,
    CONFIG_NETWORK_NAME: process.env.APP_NETWORK_NAME,

    CONFIG_TYMT_BACKEND_URL: process.env.APP_PRODUCTION_VERSION === "prod" ? process.env.APP_TYMT_BACKEND_URL : process.env.APP_TYMT_BACKEND_DEV_URL,
    CONFIG_TYMT_SOCKET_BACKEND_URL: process.env.APP_PRODUCTION_VERSION === "prod" ? process.env.APP_SOCKET_BACKEND_URL : process.env.APP_SOCKET_BACKEND_DEV_URL,
    CONFIG_TYMT_AVATAR_URL: process.env.APP_PRODUCTION_VERSION === "prod" ? process.env.APP_TYMT_AVATAR_URL : process.env.APP_TYMT_AVATAR_DEV_URL,

    CONFIG_TYMT_RELEASE_DATE: process.env.APP_TYMT_RELEASE_DATE,
    CONFIG_TYME_VERSION: process.env.APP_TYMT_VERSION,

    CONFIG_SOLAR_API_URL: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_SOLAR_API_URL : process.env.APP_TESTNET_SOLAR_API_URL,
    CONFIG_SOLAR_WSS_URL: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_SOLAR_WSS_URL : process.env.APP_TESTNET_SOLAR_WSS_URL,

    CONFIG_SOLAR_SCAN: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_SOLAR_SCAN : process.env.APP_TESTNET_SOLAR_SCAN,
    CONFIG_ETH_SCAN: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_ETH_SCAN : process.env.APP_TESTNET_ETH_SCAN,
    CONFIG_ARB_SCAN: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_ARB_SCAN : process.env.APP_TESTNET_ARB_SCAN,
    CONFIG_AVAX_SCAN: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_AVAX_SCAN : process.env.APP_TESTNET_AVAX_SCAN,
    CONFIG_BSC_SCAN: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_BSC_SCAN : process.env.APP_TESTNET_BSC_SCAN,
    CONFIG_OPT_SCAN: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_OPT_SCAN : process.env.APP_TESTNET_OPT_SCAN,
    CONFIG_POL_SCAN: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_POL_SCAN : process.env.APP_TESTNET_POL_SCAN,
    CONFIG_BTC_SCAN: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_BTC_SCAN : process.env.APP_TESTNET_BTC_SCAN,
    CONFIG_SOL_SCAN: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_SOL_SCAN : process.env.APP_TESTNET_SOL_SCAN,

    CONFIG_BSC_API_URL: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_BSC_API_URL : process.env.APP_TESTNET_BSC_API_URL,
    CONFIG_ETH_API_URL: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_ETH_API_URL : process.env.APP_TESTNET_ETH_API_URL,
    CONFIG_POL_API_URL: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_POL_API_URL : process.env.APP_TESTNET_POL_API_URL,
    CONFIG_OP_API_URL: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_OP_API_URL : process.env.APP_TESTNET_OP_API_URL,
    CONFIG_ARB_API_URL: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_ARB_API_URL : process.env.APP_TESTNET_ARB_API_URL,
    CONFIG_AVAX_API_URL: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_AVAX_API_URL : process.env.APP_TESTNET_AVAX_API_URL,
    CONFIG_BTC_API_URL: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_BTC_API_URL : process.env.APP_TESTNET_BTC_API_URL,

    CONFIG_ALCHEMY_KEY: process.env.APP_ALCHEMY_KEY,

    CONFIG_BSC_RPC_URL: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_BSC_RPC_URL : process.env.APP_TESTNET_BSC_RPC_URL,
    CONFIG_ETH_RPC_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_ETH_RPC_URL + process.env.APP_ALCHEMY_KEY
        : process.env.APP_TESTNET_ETH_RPC_URL + process.env.APP_ALCHEMY_KEY,
    CONFIG_POL_RPC_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_POL_RPC_URL + process.env.APP_ALCHEMY_KEY
        : process.env.APP_TESTNET_POL_RPC_URL + process.env.APP_ALCHEMY_KEY,
    CONFIG_OP_RPC_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_OP_RPC_URL + process.env.APP_ALCHEMY_KEY
        : process.env.APP_TESTNET_OP_RPC_URL + process.env.APP_ALCHEMY_KEY,
    CONFIG_ARB_RPC_URL:
      process.env.APP_NETWORK_NAME === "mainnet"
        ? process.env.APP_MAINNET_ARB_RPC_URL + process.env.APP_ALCHEMY_KEY
        : process.env.APP_TESTNET_ARB_RPC_URL + process.env.APP_ALCHEMY_KEY,
    CONFIG_AVAX_RPC_URL: process.env.APP_NETWORK_NAME === "mainnet" ? process.env.APP_MAINNET_AVAX_PROVIDER : process.env.APP_TESTNET_AVAX_PROVIDER,

    CONFIG_BSC_API_KEY: process.env.APP_BSC_API_KEY,
    CONFIG_ETH_API_KEY: process.env.APP_ETH_API_KEY,
    CONFIG_POL_API_KEY: process.env.APP_POL_API_KEY,
    CONFIG_OP_API_KEY: process.env.APP_OP_API_KEY,
    CONFIG_ARB_API_KEY: process.env.APP_ARB_API_KEY,
  };
  return envVars;
});
